# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd3163276c1b6461feb6cbce0007beec9b4c3b61a32a9577419ee3aa58c87d1652edee6851f29b89ea1d7c4245f63daf6814d421a659f1bda3288b9d914652f9

test:
  secret_key_base: cc277a121edce937c1c658b6427207a9200c513860aa2e18236581ed9c4c08fa262f7fa17ad2f48c96c448d020e9f1163708e4b77f4b4117b006b7d7f3bd7464

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
